openapi: 3.0.0
info:
  title: Siteki API Gateway
  version: 1.0.0

servers:
  - url: https://{api_gateway_domain}

paths:
  # HTML файлы с правильным Content-Type
  /{file}.html:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: "{file}.html"
        error_object: "fail.html"
        response_headers:
          'Content-Type': 'text/html; charset=utf-8'
          'Cache-Control': 'public, max-age=3600'
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string

  # CSS файлы
  /dist/{file}.css:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: "dist/{file}.css"
        response_headers:
          'Content-Type': 'text/css; charset=utf-8'
          'Cache-Control': 'public, max-age=86400'
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string

  # JavaScript файлы
  /{file}.js:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: "{file}.js"
        response_headers:
          'Content-Type': 'application/javascript; charset=utf-8'
          'Cache-Control': 'public, max-age=86400'
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string

  # Изображения PNG
  /{file}.png:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: "{file}.png"
        response_headers:
          'Content-Type': 'image/png'
          'Cache-Control': 'public, max-age=604800'
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string

  # Изображения JPG
  /{file}.jpg:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: "{file}.jpg"
        response_headers:
          'Content-Type': 'image/jpeg'
          'Cache-Control': 'public, max-age=604800'
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string

  # Изображения SVG
  /{file}.svg:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: "{file}.svg"
        response_headers:
          'Content-Type': 'image/svg+xml'
          'Cache-Control': 'public, max-age=604800'
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string

  # JSON файлы
  /{file}.json:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: "{file}.json"
        response_headers:
          'Content-Type': 'application/json; charset=utf-8'
          'Cache-Control': 'public, max-age=3600'
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string

  # Корневая страница
  /:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: "index.html"
        response_headers:
          'Content-Type': 'text/html; charset=utf-8'
          'Cache-Control': 'public, max-age=3600'

  # API функции
  /api/create-payment:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${create_payment_id}
      responses:
        '200':
          description: Успешное создание платежа
        '400':
          description: Ошибка валидации
        '500':
          description: Внутренняя ошибка сервера
    options:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${create_payment_id}
      responses:
        '200':
          description: CORS preflight

  /api/send-to-n8n:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${send_to_n8n_id}
      responses:
        '200':
          description: Успешная отправка в n8n
        '500':
          description: Ошибка отправки
    options:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${send_to_n8n_id}
      responses:
        '200':
          description: CORS preflight 